### ISSUE TITLE
[DB] 설계된 엔티티들을 위한 새로운 테이블 정의

### ISSUE THREAD

**Issue by zZerorok** [ssg-240304-java2/final-whiskey#22]
### 설명
설계된 회원, 권한, 신고, 리뷰, 문의, 음식점, 즐겨찾기, 이미지 엔티티들을 기반으로 데이터베이스 서버에 새로운 테이블을 정의하고 구현합니다.

### 작업 목록
- [x] 설계된 엔티티 모델 검토
- [x] 각 엔티티에 대한 DDL 스크립트 작성 (ddl-auto 로 작성)
- [x] DB 서버에 테이블 생성
- [x] #37
- [x] 엔티티 패키지 생성
- [x] 하위 패키지 생성하여 엔티티 별로 구분

**Comment by DokaDev** [comment]
스크립트 작성은 수기가 아니고 ddl-auto로 작성되었으니 수정이 필요해보입니다!
